# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jingweiyao/Desktop/SlotMC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jingweiyao/Desktop/SlotMC/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jingweiyao/Desktop/SlotMC/build/CMakeFiles /Users/jingweiyao/Desktop/SlotMC/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jingweiyao/Desktop/SlotMC/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simulator

# Build rule for target.
simulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simulator
.PHONY : simulator

# fast build rule for target.
simulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/build
.PHONY : simulator/fast

MonteCarloSimulator.o: MonteCarloSimulator.cpp.o
.PHONY : MonteCarloSimulator.o

# target to build an object file
MonteCarloSimulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/MonteCarloSimulator.cpp.o
.PHONY : MonteCarloSimulator.cpp.o

MonteCarloSimulator.i: MonteCarloSimulator.cpp.i
.PHONY : MonteCarloSimulator.i

# target to preprocess a source file
MonteCarloSimulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/MonteCarloSimulator.cpp.i
.PHONY : MonteCarloSimulator.cpp.i

MonteCarloSimulator.s: MonteCarloSimulator.cpp.s
.PHONY : MonteCarloSimulator.s

# target to generate assembly for a file
MonteCarloSimulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/MonteCarloSimulator.cpp.s
.PHONY : MonteCarloSimulator.cpp.s

MonteCarlo_main.o: MonteCarlo_main.cpp.o
.PHONY : MonteCarlo_main.o

# target to build an object file
MonteCarlo_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/MonteCarlo_main.cpp.o
.PHONY : MonteCarlo_main.cpp.o

MonteCarlo_main.i: MonteCarlo_main.cpp.i
.PHONY : MonteCarlo_main.i

# target to preprocess a source file
MonteCarlo_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/MonteCarlo_main.cpp.i
.PHONY : MonteCarlo_main.cpp.i

MonteCarlo_main.s: MonteCarlo_main.cpp.s
.PHONY : MonteCarlo_main.s

# target to generate assembly for a file
MonteCarlo_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/MonteCarlo_main.cpp.s
.PHONY : MonteCarlo_main.cpp.s

SS03Game.o: SS03Game.cpp.o
.PHONY : SS03Game.o

# target to build an object file
SS03Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/SS03Game.cpp.o
.PHONY : SS03Game.cpp.o

SS03Game.i: SS03Game.cpp.i
.PHONY : SS03Game.i

# target to preprocess a source file
SS03Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/SS03Game.cpp.i
.PHONY : SS03Game.cpp.i

SS03Game.s: SS03Game.cpp.s
.PHONY : SS03Game.s

# target to generate assembly for a file
SS03Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/SS03Game.cpp.s
.PHONY : SS03Game.cpp.s

Statistics.o: Statistics.cpp.o
.PHONY : Statistics.o

# target to build an object file
Statistics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/Statistics.cpp.o
.PHONY : Statistics.cpp.o

Statistics.i: Statistics.cpp.i
.PHONY : Statistics.i

# target to preprocess a source file
Statistics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/Statistics.cpp.i
.PHONY : Statistics.cpp.i

Statistics.s: Statistics.cpp.s
.PHONY : Statistics.s

# target to generate assembly for a file
Statistics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/Statistics.cpp.s
.PHONY : Statistics.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simulator"
	@echo "... MonteCarloSimulator.o"
	@echo "... MonteCarloSimulator.i"
	@echo "... MonteCarloSimulator.s"
	@echo "... MonteCarlo_main.o"
	@echo "... MonteCarlo_main.i"
	@echo "... MonteCarlo_main.s"
	@echo "... SS03Game.o"
	@echo "... SS03Game.i"
	@echo "... SS03Game.s"
	@echo "... Statistics.o"
	@echo "... Statistics.i"
	@echo "... Statistics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

